[package]
name = "rugix-component-set"
description = "Component compatibility evaluation for Rugix."
edition = "2021"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
anyver.workspace = true

[lints]
workspace = true
