//! Integration tests for rugix-pki using OpenSSL to generate test certificates.

use std::process::Command;
use std::time::Duration;
use std::time::SystemTime;

use cms::content_info::ContentInfo;
use cms::signed_data::SignedData;
use der::Decode;
use der::Encode;
use der::asn1::Any;
use der::asn1::OctetString;
use rugix_pki::CmsSigner;
use rugix_pki::CmsSignerBuilder;
use rugix_pki::CmsVerifier;
use rugix_pki::RsaHashAlgorithm;
use rugix_pki::RsaSignatureMode;

/// Test certificates and keys generated by OpenSSL.
struct TestPki {
    root_cert_pem: Vec<u8>,
    signer_cert_pem: Vec<u8>,
    signer_key_pem: Vec<u8>,
    other_root_cert_pem: Vec<u8>,
    temp_dir: tempfile::TempDir,
}

impl TestPki {
    fn new() -> Self {
        let temp_dir = tempfile::tempdir().expect("failed to create temp dir");
        let dir = temp_dir.path();

        let ee_ext_path = dir.join("ee.ext");
        std::fs::write(
            &ee_ext_path,
            "basicConstraints=critical,CA:FALSE\nkeyUsage=digitalSignature\n",
        )
        .expect("failed to write EE extensions");

        let root_key_path = dir.join("root.key");
        let root_cert_path = dir.join("root.crt");

        let status = Command::new("openssl")
            .args([
                "ecparam",
                "-name",
                "prime256v1",
                "-genkey",
                "-noout",
                "-out",
            ])
            .arg(&root_key_path)
            .status()
            .expect("failed to generate root key");
        assert!(status.success(), "failed to generate root key");

        let status = Command::new("openssl")
            .args(["req", "-x509", "-new", "-key"])
            .arg(&root_key_path)
            .args(["-out"])
            .arg(&root_cert_path)
            .args(["-days", "3650", "-subj", "/CN=Test Root CA"])
            .args(["-addext", "basicConstraints=critical,CA:TRUE"])
            .args(["-addext", "keyUsage=keyCertSign,cRLSign"])
            .status()
            .expect("failed to generate root cert");
        assert!(status.success(), "failed to generate root cert");

        let signer_key_path = dir.join("signer.key");
        let signer_csr_path = dir.join("signer.csr");
        let signer_cert_path = dir.join("signer.crt");

        let status = Command::new("openssl")
            .args([
                "ecparam",
                "-name",
                "prime256v1",
                "-genkey",
                "-noout",
                "-out",
            ])
            .arg(&signer_key_path)
            .status()
            .expect("failed to generate signer key");
        assert!(status.success(), "failed to generate signer key");

        let status = Command::new("openssl")
            .args(["req", "-new", "-key"])
            .arg(&signer_key_path)
            .args(["-out"])
            .arg(&signer_csr_path)
            .args(["-subj", "/CN=Test Signer"])
            .status()
            .expect("failed to generate signer csr");
        assert!(status.success(), "failed to generate signer csr");

        let status = Command::new("openssl")
            .args(["x509", "-req", "-in"])
            .arg(&signer_csr_path)
            .args(["-CA"])
            .arg(&root_cert_path)
            .args(["-CAkey"])
            .arg(&root_key_path)
            .args(["-CAcreateserial", "-out"])
            .arg(&signer_cert_path)
            .args(["-days", "365"])
            .args(["-extfile"])
            .arg(&ee_ext_path)
            .status()
            .expect("failed to generate signer cert");
        assert!(status.success(), "failed to generate signer cert");

        let other_root_key_path = dir.join("other_root.key");
        let other_root_cert_path = dir.join("other_root.crt");

        let status = Command::new("openssl")
            .args([
                "ecparam",
                "-name",
                "prime256v1",
                "-genkey",
                "-noout",
                "-out",
            ])
            .arg(&other_root_key_path)
            .status()
            .expect("failed to generate other root key");
        assert!(status.success(), "failed to generate other root key");

        let status = Command::new("openssl")
            .args(["req", "-x509", "-new", "-key"])
            .arg(&other_root_key_path)
            .args(["-out"])
            .arg(&other_root_cert_path)
            .args(["-days", "3650", "-subj", "/CN=Other Root CA"])
            .args(["-addext", "basicConstraints=critical,CA:TRUE"])
            .args(["-addext", "keyUsage=keyCertSign,cRLSign"])
            .status()
            .expect("failed to generate other root cert");
        assert!(status.success(), "failed to generate other root cert");

        let root_cert_pem = std::fs::read(&root_cert_path).expect("failed to read root cert");
        let signer_cert_pem = std::fs::read(&signer_cert_path).expect("failed to read signer cert");
        let signer_key_pem = std::fs::read(&signer_key_path).expect("failed to read signer key");
        let other_root_cert_pem =
            std::fs::read(&other_root_cert_path).expect("failed to read other root cert");

        Self {
            root_cert_pem,
            signer_cert_pem,
            signer_key_pem,
            other_root_cert_pem,
            temp_dir,
        }
    }

    fn openssl_sign(&self, data: &[u8], extra_args: &[&str]) -> Vec<u8> {
        let dir = self.temp_dir.path();
        let data_path = dir.join("openssl-input.bin");
        let signer_cert_path = dir.join("openssl-signer.crt");
        let signer_key_path = dir.join("openssl-signer.key");
        let signature_path = dir.join("openssl-signature.cms");
        std::fs::write(&data_path, data).expect("failed to write OpenSSL input");
        std::fs::write(&signer_cert_path, &self.signer_cert_pem)
            .expect("failed to write OpenSSL signer certificate");
        std::fs::write(&signer_key_path, &self.signer_key_pem)
            .expect("failed to write OpenSSL signer key");
        let status = Command::new("openssl")
            .args(["cms", "-sign", "-in"])
            .arg(&data_path)
            .args(["-signer"])
            .arg(&signer_cert_path)
            .args(["-inkey"])
            .arg(&signer_key_path)
            .args(["-out"])
            .arg(&signature_path)
            .args(["-outform", "DER", "-nodetach", "-binary"])
            .args(extra_args)
            .status()
            .expect("failed to run OpenSSL CMS signing");
        assert!(status.success(), "OpenSSL CMS signing failed");
        std::fs::read(signature_path).expect("failed to read OpenSSL signature")
    }
}

#[test]
fn test_verification_accepts_rotated_roots_in_either_order() {
    let pki = TestPki::new();
    let signature = CmsSigner::new(&pki.signer_cert_pem, &pki.signer_key_pem)
        .unwrap()
        .sign(b"root rotation")
        .unwrap();

    for roots in [
        [&pki.other_root_cert_pem, &pki.root_cert_pem],
        [&pki.root_cert_pem, &pki.other_root_cert_pem],
    ] {
        assert!(roots.iter().any(|root| {
            CmsVerifier::new(root)
                .and_then(|verifier| verifier.verify(&signature))
                .is_ok()
        }));
    }
}

#[test]
fn test_openssl_id_data_without_signed_attributes() {
    let pki = TestPki::new();
    let signature = pki.openssl_sign(b"no signed attributes", &["-noattr"]);
    let result = CmsVerifier::new(&pki.root_cert_pem)
        .unwrap()
        .verify(&signature)
        .unwrap();
    assert_eq!(result.content, b"no signed attributes");
}

#[test]
fn test_subject_key_identifier_signer_id() {
    let pki = TestPki::new();
    let signature = pki.openssl_sign(b"subject key identifier", &["-keyid"]);
    let result = CmsVerifier::new(&pki.root_cert_pem)
        .unwrap()
        .verify(&signature)
        .unwrap();
    assert_eq!(result.content, b"subject key identifier");
}

#[test]
fn test_later_signer_info_is_tried_after_an_invalid_one() {
    let pki = TestPki::new();
    let signature = CmsSigner::new(&pki.signer_cert_pem, &pki.signer_key_pem)
        .unwrap()
        .sign(b"multiple signer infos")
        .unwrap();
    let mut content_info = ContentInfo::from_der(&signature).unwrap();
    let mut signed_data = content_info.content.decode_as::<SignedData>().unwrap();
    let mut invalid = signed_data.signer_infos.0.iter().next().unwrap().clone();
    invalid.signature = OctetString::new(vec![0; invalid.signature.as_bytes().len()]).unwrap();
    signed_data.signer_infos.0.insert(invalid).unwrap();
    assert_eq!(signed_data.signer_infos.0.len(), 2);
    content_info.content = Any::from_der(&signed_data.to_der().unwrap()).unwrap();

    let result = CmsVerifier::new(&pki.root_cert_pem)
        .unwrap()
        .verify(&content_info.to_der().unwrap())
        .unwrap();
    assert_eq!(result.content, b"multiple signer infos");
}

#[test]
fn test_sign_and_verify() {
    let pki = TestPki::new();
    let data = b"Hello, World!";

    let signer =
        CmsSigner::new(&pki.signer_cert_pem, &pki.signer_key_pem).expect("failed to create signer");
    let signature = signer.sign(data).expect("failed to sign");

    let verifier = CmsVerifier::new(&pki.root_cert_pem).expect("failed to create verifier");
    let result = verifier.verify(&signature).expect("failed to verify");
    assert_eq!(result.content, data);

    let signing_time = result.signing_time.expect("signing time should be present");
    let elapsed = SystemTime::now()
        .duration_since(signing_time)
        .expect("signing time should be in the past");
    assert!(
        elapsed < Duration::from_secs(60),
        "signing time should be recent, got {:?} ago",
        elapsed
    );
}

#[test]
fn test_verify_wrong_root() {
    let pki = TestPki::new();
    let data = b"Hello, World!";

    let signer =
        CmsSigner::new(&pki.signer_cert_pem, &pki.signer_key_pem).expect("failed to create signer");
    let signature = signer.sign(data).expect("failed to sign");

    let verifier = CmsVerifier::new(&pki.other_root_cert_pem)
        .expect("failed to create verifier with wrong root");
    let result = verifier.verify(&signature);
    assert!(result.is_err(), "verification should fail with wrong root");
}

#[test]
fn test_verify_content() {
    let pki = TestPki::new();
    let data = b"Hello, World!";

    let signer =
        CmsSigner::new(&pki.signer_cert_pem, &pki.signer_key_pem).expect("failed to create signer");
    let signature = signer.sign(data).expect("failed to sign");

    let verifier = CmsVerifier::new(&pki.root_cert_pem).expect("failed to create verifier");
    verifier
        .verify_content(&signature, data)
        .expect("verify_content should succeed");

    let result = verifier.verify_content(&signature, b"wrong data");
    assert!(
        result.is_err(),
        "verify_content should fail with wrong data"
    );
}

#[test]
fn test_openssl_interop_verify_our_signature() {
    let pki = TestPki::new();
    let dir = pki.temp_dir.path();
    let data = b"Hello from Rust!";

    let signer =
        CmsSigner::new(&pki.signer_cert_pem, &pki.signer_key_pem).expect("failed to create signer");
    let signature = signer.sign(data).expect("failed to sign");

    let sig_path = dir.join("signature.cms");
    std::fs::write(&sig_path, &signature).expect("failed to write signature");

    let root_path = dir.join("root.crt");
    std::fs::write(&root_path, &pki.root_cert_pem).expect("failed to write root cert");

    let output_path = dir.join("output.bin");
    let status = Command::new("openssl")
        .args(["cms", "-verify", "-in"])
        .arg(&sig_path)
        .args(["-inform", "DER", "-out"])
        .arg(&output_path)
        .args([
            "-no-CAfile",
            "-no-CApath",
            "-no-CAstore",
            "-verify_retcode",
            "-CAfile",
        ])
        .arg(&root_path)
        .status()
        .expect("failed to run openssl verify");

    assert!(
        status.success(),
        "OpenSSL should successfully verify our signature"
    );

    let extracted = std::fs::read(&output_path).expect("failed to read output");
    assert_eq!(extracted, data, "extracted content should match");
}

#[test]
fn test_openssl_interop_sign_with_openssl() {
    let pki = TestPki::new();
    let dir = pki.temp_dir.path();
    let data = b"Hello from OpenSSL!";

    let data_path = dir.join("data.bin");
    std::fs::write(&data_path, data).expect("failed to write data");

    let root_path = dir.join("root.crt");
    std::fs::write(&root_path, &pki.root_cert_pem).expect("failed to write root cert");

    let signer_cert_path = dir.join("signer.crt");
    std::fs::write(&signer_cert_path, &pki.signer_cert_pem).expect("failed to write signer cert");

    let signer_key_path = dir.join("signer.key");
    std::fs::write(&signer_key_path, &pki.signer_key_pem).expect("failed to write signer key");

    let sig_path = dir.join("signature.cms");
    let status = Command::new("openssl")
        .args(["cms", "-sign", "-in"])
        .arg(&data_path)
        .args(["-signer"])
        .arg(&signer_cert_path)
        .args(["-inkey"])
        .arg(&signer_key_path)
        .args(["-out"])
        .arg(&sig_path)
        .args(["-outform", "DER", "-nosmimecap", "-nodetach", "-binary"])
        .status()
        .expect("failed to run openssl sign");

    assert!(
        status.success(),
        "OpenSSL should successfully sign the data"
    );

    let signature = std::fs::read(&sig_path).expect("failed to read signature");
    let verifier = CmsVerifier::new(&pki.root_cert_pem).expect("failed to create verifier");
    let result = verifier
        .verify(&signature)
        .expect("failed to verify OpenSSL signature");
    assert_eq!(result.content, data, "content should match");
}

#[test]
fn test_signer_builder() {
    let pki = TestPki::new();
    let data = b"Builder test data";

    let signer = CmsSignerBuilder::new(&pki.signer_cert_pem, &pki.signer_key_pem)
        .expect("failed to create builder")
        .build()
        .expect("failed to build signer");
    let signature = signer.sign(data).expect("failed to sign");

    let verifier = CmsVerifier::new(&pki.root_cert_pem).expect("failed to create verifier");
    let result = verifier.verify(&signature).expect("failed to verify");
    assert_eq!(result.content, data);
}

#[test]
fn test_custom_signing_time() {
    let pki = TestPki::new();
    let data = b"Custom signing time test";

    // Use a fixed time: 2025-01-15 12:00:00 UTC (well within UtcTime range).
    let fixed_time = SystemTime::UNIX_EPOCH + Duration::from_secs(1736942400);

    let signer = CmsSignerBuilder::new(&pki.signer_cert_pem, &pki.signer_key_pem)
        .expect("failed to create builder")
        .with_signing_time(fixed_time)
        .build()
        .expect("failed to build signer");
    let signature = signer.sign(data).expect("failed to sign");

    let verifier = CmsVerifier::new(&pki.root_cert_pem).expect("failed to create verifier");
    let result = verifier.verify(&signature).expect("failed to verify");
    assert_eq!(result.content, data);

    let signing_time = result.signing_time.expect("signing time should be present");
    assert_eq!(
        signing_time
            .duration_since(SystemTime::UNIX_EPOCH)
            .unwrap()
            .as_secs(),
        fixed_time
            .duration_since(SystemTime::UNIX_EPOCH)
            .unwrap()
            .as_secs(),
        "signing time should match the configured value"
    );
}

#[test]
fn test_large_data() {
    let pki = TestPki::new();
    let data: Vec<u8> = (0..1024 * 1024).map(|i| (i % 256) as u8).collect();

    let signer =
        CmsSigner::new(&pki.signer_cert_pem, &pki.signer_key_pem).expect("failed to create signer");
    let signature = signer.sign(&data).expect("failed to sign large data");

    let verifier = CmsVerifier::new(&pki.root_cert_pem).expect("failed to create verifier");
    let result = verifier
        .verify(&signature)
        .expect("failed to verify large data");
    assert_eq!(result.content, data);
}

#[test]
fn test_empty_data() {
    let pki = TestPki::new();
    let data = b"";

    let signer =
        CmsSigner::new(&pki.signer_cert_pem, &pki.signer_key_pem).expect("failed to create signer");
    let signature = signer.sign(data).expect("failed to sign empty data");

    let verifier = CmsVerifier::new(&pki.root_cert_pem).expect("failed to create verifier");
    let result = verifier
        .verify(&signature)
        .expect("failed to verify empty data");
    assert_eq!(result.content, data.as_slice());
}

/// Test PKI with intermediate certificate.
struct TestPkiWithIntermediate {
    root_cert_pem: Vec<u8>,
    intermediate_cert_pem: Vec<u8>,
    signer_cert_pem: Vec<u8>,
    signer_key_pem: Vec<u8>,
    #[allow(dead_code)]
    temp_dir: tempfile::TempDir,
}

impl TestPkiWithIntermediate {
    fn new() -> Self {
        let temp_dir = tempfile::tempdir().expect("failed to create temp dir");
        let dir = temp_dir.path();

        let ee_ext_path = dir.join("ee.ext");
        std::fs::write(
            &ee_ext_path,
            "basicConstraints=critical,CA:FALSE\nkeyUsage=digitalSignature\n",
        )
        .expect("failed to write EE extensions");

        let root_key_path = dir.join("root.key");
        let root_cert_path = dir.join("root.crt");

        let status = Command::new("openssl")
            .args([
                "ecparam",
                "-name",
                "prime256v1",
                "-genkey",
                "-noout",
                "-out",
            ])
            .arg(&root_key_path)
            .status()
            .expect("failed to generate root key");
        assert!(status.success());

        let status = Command::new("openssl")
            .args(["req", "-x509", "-new", "-key"])
            .arg(&root_key_path)
            .args(["-out"])
            .arg(&root_cert_path)
            .args(["-days", "3650", "-subj", "/CN=Test Root CA"])
            .args(["-addext", "basicConstraints=critical,CA:TRUE"])
            .args(["-addext", "keyUsage=keyCertSign,cRLSign"])
            .status()
            .expect("failed to generate root cert");
        assert!(status.success());

        let intermediate_key_path = dir.join("intermediate.key");
        let intermediate_csr_path = dir.join("intermediate.csr");
        let intermediate_cert_path = dir.join("intermediate.crt");
        let intermediate_ext_path = dir.join("intermediate.ext");

        let status = Command::new("openssl")
            .args([
                "ecparam",
                "-name",
                "prime256v1",
                "-genkey",
                "-noout",
                "-out",
            ])
            .arg(&intermediate_key_path)
            .status()
            .expect("failed to generate intermediate key");
        assert!(status.success());

        let status = Command::new("openssl")
            .args(["req", "-new", "-key"])
            .arg(&intermediate_key_path)
            .args(["-out"])
            .arg(&intermediate_csr_path)
            .args(["-subj", "/CN=Test Intermediate CA"])
            .status()
            .expect("failed to generate intermediate csr");
        assert!(status.success());

        std::fs::write(
            &intermediate_ext_path,
            "[v3_ca]\n\
basicConstraints = CA:TRUE\n\
keyUsage = keyCertSign, cRLSign\n",
        )
        .expect("failed to write intermediate extensions");

        let status = Command::new("openssl")
            .args(["x509", "-req", "-in"])
            .arg(&intermediate_csr_path)
            .args(["-CA"])
            .arg(&root_cert_path)
            .args(["-CAkey"])
            .arg(&root_key_path)
            .args(["-CAcreateserial", "-out"])
            .arg(&intermediate_cert_path)
            .args(["-extfile"])
            .arg(&intermediate_ext_path)
            .args(["-extensions", "v3_ca"])
            .args(["-days", "1825"])
            .status()
            .expect("failed to generate intermediate cert");
        assert!(status.success());

        let signer_key_path = dir.join("signer.key");
        let signer_csr_path = dir.join("signer.csr");
        let signer_cert_path = dir.join("signer.crt");

        let status = Command::new("openssl")
            .args([
                "ecparam",
                "-name",
                "prime256v1",
                "-genkey",
                "-noout",
                "-out",
            ])
            .arg(&signer_key_path)
            .status()
            .expect("failed to generate signer key");
        assert!(status.success());

        let status = Command::new("openssl")
            .args(["req", "-new", "-key"])
            .arg(&signer_key_path)
            .args(["-out"])
            .arg(&signer_csr_path)
            .args(["-subj", "/CN=Test Signer"])
            .status()
            .expect("failed to generate signer csr");
        assert!(status.success());

        let status = Command::new("openssl")
            .args(["x509", "-req", "-in"])
            .arg(&signer_csr_path)
            .args(["-CA"])
            .arg(&intermediate_cert_path)
            .args(["-CAkey"])
            .arg(&intermediate_key_path)
            .args(["-CAcreateserial", "-out"])
            .arg(&signer_cert_path)
            .args(["-days", "365"])
            .args(["-extfile"])
            .arg(&ee_ext_path)
            .status()
            .expect("failed to generate signer cert");
        assert!(status.success());

        let root_cert_pem = std::fs::read(&root_cert_path).expect("failed to read root cert");
        let intermediate_cert_pem =
            std::fs::read(&intermediate_cert_path).expect("failed to read intermediate cert");
        let signer_cert_pem = std::fs::read(&signer_cert_path).expect("failed to read signer cert");
        let signer_key_pem = std::fs::read(&signer_key_path).expect("failed to read signer key");

        Self {
            root_cert_pem,
            intermediate_cert_pem,
            signer_cert_pem,
            signer_key_pem,
            temp_dir,
        }
    }
}

#[test]
fn test_certificate_chain_with_intermediate() {
    let pki = TestPkiWithIntermediate::new();
    let data = b"Data signed with intermediate cert chain";

    let signer = CmsSignerBuilder::new(&pki.signer_cert_pem, &pki.signer_key_pem)
        .expect("failed to create builder")
        .with_intermediate_cert(&pki.intermediate_cert_pem)
        .expect("failed to add intermediate cert")
        .build()
        .expect("failed to build signer");
    let signature = signer.sign(data).expect("failed to sign");

    let verifier = CmsVerifier::new(&pki.root_cert_pem).expect("failed to create verifier");
    let result = verifier.verify(&signature).expect("failed to verify");
    assert_eq!(result.content, data);
    assert_eq!(
        result.certificate_chain.len(),
        3,
        "chain should have 3 certs"
    );
}

/// Test PKI with RSA keys for RSA-PSS testing.
struct TestPkiRsa {
    root_cert_pem: Vec<u8>,
    signer_cert_pem: Vec<u8>,
    signer_key_pem: Vec<u8>,
    #[allow(dead_code)]
    temp_dir: tempfile::TempDir,
}

impl TestPkiRsa {
    fn new() -> Self {
        let temp_dir = tempfile::tempdir().expect("failed to create temp dir");
        let dir = temp_dir.path();

        let ee_ext_path = dir.join("ee.ext");
        std::fs::write(
            &ee_ext_path,
            "basicConstraints=critical,CA:FALSE\nkeyUsage=digitalSignature\n",
        )
        .expect("failed to write EE extensions");

        let root_key_path = dir.join("root.key");
        let root_cert_path = dir.join("root.crt");

        let status = Command::new("openssl")
            .args(["genrsa", "-out"])
            .arg(&root_key_path)
            .args(["2048"])
            .status()
            .expect("failed to generate RSA root key");
        assert!(status.success());

        let status = Command::new("openssl")
            .args(["req", "-x509", "-new", "-key"])
            .arg(&root_key_path)
            .args(["-out"])
            .arg(&root_cert_path)
            .args(["-days", "3650", "-subj", "/CN=Test RSA Root CA"])
            .args(["-addext", "basicConstraints=critical,CA:TRUE"])
            .args(["-addext", "keyUsage=keyCertSign,cRLSign"])
            .status()
            .expect("failed to generate RSA root cert");
        assert!(status.success());

        let signer_key_path = dir.join("signer.key");
        let signer_csr_path = dir.join("signer.csr");
        let signer_cert_path = dir.join("signer.crt");

        let status = Command::new("openssl")
            .args(["genrsa", "-out"])
            .arg(&signer_key_path)
            .args(["2048"])
            .status()
            .expect("failed to generate RSA signer key");
        assert!(status.success());

        let status = Command::new("openssl")
            .args(["req", "-new", "-key"])
            .arg(&signer_key_path)
            .args(["-out"])
            .arg(&signer_csr_path)
            .args(["-subj", "/CN=Test RSA Signer"])
            .status()
            .expect("failed to generate RSA signer csr");
        assert!(status.success());

        let status = Command::new("openssl")
            .args(["x509", "-req", "-in"])
            .arg(&signer_csr_path)
            .args(["-CA"])
            .arg(&root_cert_path)
            .args(["-CAkey"])
            .arg(&root_key_path)
            .args(["-CAcreateserial", "-out"])
            .arg(&signer_cert_path)
            .args(["-days", "365"])
            .args(["-extfile"])
            .arg(&ee_ext_path)
            .status()
            .expect("failed to generate RSA signer cert");
        assert!(status.success());

        let root_cert_pem = std::fs::read(&root_cert_path).expect("failed to read root cert");
        let signer_cert_pem = std::fs::read(&signer_cert_path).expect("failed to read signer cert");
        let signer_key_pem = std::fs::read(&signer_key_path).expect("failed to read signer key");

        Self {
            root_cert_pem,
            signer_cert_pem,
            signer_key_pem,
            temp_dir,
        }
    }
}

#[test]
fn test_rsa_pss_sign_and_verify() {
    let pki = TestPkiRsa::new();
    let data = b"RSA-PSS signed data";

    let signer = CmsSignerBuilder::new(&pki.signer_cert_pem, &pki.signer_key_pem)
        .expect("failed to create builder")
        .with_rsa_mode(RsaSignatureMode::Pss)
        .with_rsa_hash(RsaHashAlgorithm::Sha256)
        .build()
        .expect("failed to build signer");
    assert_eq!(
        signer.algorithm(),
        rugix_pki::SignatureAlgorithm::RsaPssSha256
    );

    let signature = signer.sign(data).expect("failed to sign with RSA-PSS");
    let verifier = CmsVerifier::new(&pki.root_cert_pem).expect("failed to create verifier");
    let result = verifier
        .verify(&signature)
        .expect("failed to verify RSA-PSS signature");
    assert_eq!(result.content, data);
}

#[test]
fn test_rsa_pss_sha384() {
    let pki = TestPkiRsa::new();
    let data = b"RSA-PSS SHA-384 signed data";

    let signer = CmsSignerBuilder::new(&pki.signer_cert_pem, &pki.signer_key_pem)
        .expect("failed to create builder")
        .with_rsa_mode(RsaSignatureMode::Pss)
        .with_rsa_hash(RsaHashAlgorithm::Sha384)
        .build()
        .expect("failed to build signer");
    assert_eq!(
        signer.algorithm(),
        rugix_pki::SignatureAlgorithm::RsaPssSha384
    );

    let signature = signer.sign(data).expect("failed to sign");
    let verifier = CmsVerifier::new(&pki.root_cert_pem).expect("failed to create verifier");
    let result = verifier.verify(&signature).expect("failed to verify");
    assert_eq!(result.content, data);
}

#[test]
fn test_rsa_pss_sha512() {
    let pki = TestPkiRsa::new();
    let data = b"RSA-PSS SHA-512 signed data";

    let signer = CmsSignerBuilder::new(&pki.signer_cert_pem, &pki.signer_key_pem)
        .expect("failed to create builder")
        .with_rsa_mode(RsaSignatureMode::Pss)
        .with_rsa_hash(RsaHashAlgorithm::Sha512)
        .build()
        .expect("failed to build signer");
    assert_eq!(
        signer.algorithm(),
        rugix_pki::SignatureAlgorithm::RsaPssSha512
    );

    let signature = signer.sign(data).expect("failed to sign");
    let verifier = CmsVerifier::new(&pki.root_cert_pem).expect("failed to create verifier");
    let result = verifier.verify(&signature).expect("failed to verify");
    assert_eq!(result.content, data);
}

#[test]
fn test_rsa_pss_default() {
    let pki = TestPkiRsa::new();
    let data = b"RSA-PSS signed data (default)";

    let signer =
        CmsSigner::new(&pki.signer_cert_pem, &pki.signer_key_pem).expect("failed to create signer");
    assert_eq!(
        signer.algorithm(),
        rugix_pki::SignatureAlgorithm::RsaPssSha256
    );

    let signature = signer.sign(data).expect("failed to sign");
    let verifier = CmsVerifier::new(&pki.root_cert_pem).expect("failed to create verifier");
    let result = verifier.verify(&signature).expect("failed to verify");
    assert_eq!(result.content, data);
}

#[test]
fn test_rsa_pkcs1v15_opt_in() {
    let pki = TestPkiRsa::new();
    let data = b"RSA PKCS#1 v1.5 signed data";

    let signer = CmsSignerBuilder::new(&pki.signer_cert_pem, &pki.signer_key_pem)
        .expect("failed to create builder")
        .with_rsa_mode(RsaSignatureMode::Pkcs1v15)
        .build()
        .expect("failed to build signer");
    assert_eq!(
        signer.algorithm(),
        rugix_pki::SignatureAlgorithm::RsaPkcs1Sha256
    );

    let signature = signer.sign(data).expect("failed to sign");
    let verifier = CmsVerifier::new(&pki.root_cert_pem).expect("failed to create verifier");
    let result = verifier.verify(&signature).expect("failed to verify");
    assert_eq!(result.content, data);
}

/// Test PKI with Ed25519 keys.
struct TestPkiEd25519 {
    root_cert_pem: Vec<u8>,
    signer_cert_pem: Vec<u8>,
    signer_key_pem: Vec<u8>,
    #[allow(dead_code)]
    temp_dir: tempfile::TempDir,
}

impl TestPkiEd25519 {
    fn new() -> Self {
        let temp_dir = tempfile::tempdir().expect("failed to create temp dir");
        let dir = temp_dir.path();

        let ee_ext_path = dir.join("ee.ext");
        std::fs::write(
            &ee_ext_path,
            "basicConstraints=critical,CA:FALSE\nkeyUsage=digitalSignature\n",
        )
        .expect("failed to write EE extensions");

        let root_key_path = dir.join("root.key");
        let root_cert_path = dir.join("root.crt");

        let status = Command::new("openssl")
            .args(["genpkey", "-algorithm", "ED25519", "-out"])
            .arg(&root_key_path)
            .status()
            .expect("failed to generate Ed25519 root key");
        assert!(status.success(), "failed to generate Ed25519 root key");

        let status = Command::new("openssl")
            .args(["req", "-x509", "-new", "-key"])
            .arg(&root_key_path)
            .args(["-out"])
            .arg(&root_cert_path)
            .args(["-days", "3650", "-subj", "/CN=Test Ed25519 Root CA"])
            .args(["-addext", "basicConstraints=critical,CA:TRUE"])
            .args(["-addext", "keyUsage=keyCertSign,cRLSign"])
            .status()
            .expect("failed to generate Ed25519 root cert");
        assert!(status.success(), "failed to generate Ed25519 root cert");

        let signer_key_path = dir.join("signer.key");
        let signer_csr_path = dir.join("signer.csr");
        let signer_cert_path = dir.join("signer.crt");

        let status = Command::new("openssl")
            .args(["genpkey", "-algorithm", "ED25519", "-out"])
            .arg(&signer_key_path)
            .status()
            .expect("failed to generate Ed25519 signer key");
        assert!(status.success(), "failed to generate Ed25519 signer key");

        let status = Command::new("openssl")
            .args(["req", "-new", "-key"])
            .arg(&signer_key_path)
            .args(["-out"])
            .arg(&signer_csr_path)
            .args(["-subj", "/CN=Test Ed25519 Signer"])
            .status()
            .expect("failed to generate Ed25519 signer csr");
        assert!(status.success(), "failed to generate Ed25519 signer csr");

        let status = Command::new("openssl")
            .args(["x509", "-req", "-in"])
            .arg(&signer_csr_path)
            .args(["-CA"])
            .arg(&root_cert_path)
            .args(["-CAkey"])
            .arg(&root_key_path)
            .args(["-CAcreateserial", "-out"])
            .arg(&signer_cert_path)
            .args(["-days", "365"])
            .args(["-extfile"])
            .arg(&ee_ext_path)
            .status()
            .expect("failed to generate Ed25519 signer cert");
        assert!(status.success(), "failed to generate Ed25519 signer cert");

        let root_cert_pem = std::fs::read(&root_cert_path).expect("failed to read root cert");
        let signer_cert_pem = std::fs::read(&signer_cert_path).expect("failed to read signer cert");
        let signer_key_pem = std::fs::read(&signer_key_path).expect("failed to read signer key");

        Self {
            root_cert_pem,
            signer_cert_pem,
            signer_key_pem,
            temp_dir,
        }
    }
}

#[test]
fn test_ed25519_sign_and_verify() {
    let pki = TestPkiEd25519::new();
    let data = b"Ed25519 signed data";

    let signer =
        CmsSigner::new(&pki.signer_cert_pem, &pki.signer_key_pem).expect("failed to create signer");
    assert_eq!(signer.algorithm(), rugix_pki::SignatureAlgorithm::Ed25519);

    let signature = signer.sign(data).expect("failed to sign with Ed25519");
    let verifier = CmsVerifier::new(&pki.root_cert_pem).expect("failed to create verifier");
    let result = verifier
        .verify(&signature)
        .expect("failed to verify Ed25519 signature");
    assert_eq!(result.content, data);
}

#[test]
fn test_ec_key_mismatch() {
    let temp_dir = tempfile::tempdir().expect("failed to create temp dir");
    let dir = temp_dir.path();

    let ee_ext_path = dir.join("ee.ext");
    std::fs::write(
        &ee_ext_path,
        "basicConstraints=critical,CA:FALSE\nkeyUsage=digitalSignature\n",
    )
    .expect("failed to write EE extensions");

    // Generate a root CA.
    let root_key_path = dir.join("root.key");
    let root_cert_path = dir.join("root.crt");
    assert!(
        Command::new("openssl")
            .args([
                "ecparam",
                "-name",
                "prime256v1",
                "-genkey",
                "-noout",
                "-out"
            ])
            .arg(&root_key_path)
            .status()
            .unwrap()
            .success()
    );
    assert!(
        Command::new("openssl")
            .args(["req", "-x509", "-new", "-key"])
            .arg(&root_key_path)
            .args(["-out"])
            .arg(&root_cert_path)
            .args(["-days", "3650", "-subj", "/CN=Test Root CA"])
            .args(["-addext", "basicConstraints=critical,CA:TRUE"])
            .args(["-addext", "keyUsage=keyCertSign,cRLSign"])
            .status()
            .unwrap()
            .success()
    );

    // Generate the signer key and certificate.
    let signer_key_path = dir.join("signer.key");
    let signer_csr_path = dir.join("signer.csr");
    let signer_cert_path = dir.join("signer.crt");
    assert!(
        Command::new("openssl")
            .args([
                "ecparam",
                "-name",
                "prime256v1",
                "-genkey",
                "-noout",
                "-out"
            ])
            .arg(&signer_key_path)
            .status()
            .unwrap()
            .success()
    );
    assert!(
        Command::new("openssl")
            .args(["req", "-new", "-key"])
            .arg(&signer_key_path)
            .args(["-out"])
            .arg(&signer_csr_path)
            .args(["-subj", "/CN=Test Signer"])
            .status()
            .unwrap()
            .success()
    );
    assert!(
        Command::new("openssl")
            .args(["x509", "-req", "-in"])
            .arg(&signer_csr_path)
            .args(["-CA"])
            .arg(&root_cert_path)
            .args(["-CAkey"])
            .arg(&root_key_path)
            .args(["-CAcreateserial", "-out"])
            .arg(&signer_cert_path)
            .args(["-days", "365", "-extfile"])
            .arg(&ee_ext_path)
            .status()
            .unwrap()
            .success()
    );

    // Generate a different EC key (same curve, different key pair).
    let wrong_key_path = dir.join("wrong.key");
    assert!(
        Command::new("openssl")
            .args([
                "ecparam",
                "-name",
                "prime256v1",
                "-genkey",
                "-noout",
                "-out"
            ])
            .arg(&wrong_key_path)
            .status()
            .unwrap()
            .success()
    );

    let signer_cert_pem = std::fs::read(&signer_cert_path).unwrap();
    let wrong_key_pem = std::fs::read(&wrong_key_path).unwrap();

    let err = CmsSigner::new(&signer_cert_pem, &wrong_key_pem)
        .err()
        .expect("should fail when private key doesn't match certificate");
    assert!(
        err.to_string().contains("does not match"),
        "error should indicate key mismatch, got: {}",
        err
    );
}

#[test]
fn test_rsa_key_mismatch() {
    let temp_dir = tempfile::tempdir().expect("failed to create temp dir");
    let dir = temp_dir.path();

    let ee_ext_path = dir.join("ee.ext");
    std::fs::write(
        &ee_ext_path,
        "basicConstraints=critical,CA:FALSE\nkeyUsage=digitalSignature\n",
    )
    .expect("failed to write EE extensions");

    // Generate a root CA.
    let root_key_path = dir.join("root.key");
    let root_cert_path = dir.join("root.crt");
    assert!(
        Command::new("openssl")
            .args(["genrsa", "-out"])
            .arg(&root_key_path)
            .args(["2048"])
            .status()
            .unwrap()
            .success()
    );
    assert!(
        Command::new("openssl")
            .args(["req", "-x509", "-new", "-key"])
            .arg(&root_key_path)
            .args(["-out"])
            .arg(&root_cert_path)
            .args(["-days", "3650", "-subj", "/CN=Test RSA Root CA"])
            .args(["-addext", "basicConstraints=critical,CA:TRUE"])
            .args(["-addext", "keyUsage=keyCertSign,cRLSign"])
            .status()
            .unwrap()
            .success()
    );

    // Generate the signer key and certificate.
    let signer_key_path = dir.join("signer.key");
    let signer_csr_path = dir.join("signer.csr");
    let signer_cert_path = dir.join("signer.crt");
    assert!(
        Command::new("openssl")
            .args(["genrsa", "-out"])
            .arg(&signer_key_path)
            .args(["2048"])
            .status()
            .unwrap()
            .success()
    );
    assert!(
        Command::new("openssl")
            .args(["req", "-new", "-key"])
            .arg(&signer_key_path)
            .args(["-out"])
            .arg(&signer_csr_path)
            .args(["-subj", "/CN=Test RSA Signer"])
            .status()
            .unwrap()
            .success()
    );
    assert!(
        Command::new("openssl")
            .args(["x509", "-req", "-in"])
            .arg(&signer_csr_path)
            .args(["-CA"])
            .arg(&root_cert_path)
            .args(["-CAkey"])
            .arg(&root_key_path)
            .args(["-CAcreateserial", "-out"])
            .arg(&signer_cert_path)
            .args(["-days", "365", "-extfile"])
            .arg(&ee_ext_path)
            .status()
            .unwrap()
            .success()
    );

    // Generate a different RSA key.
    let wrong_key_path = dir.join("wrong.key");
    assert!(
        Command::new("openssl")
            .args(["genrsa", "-out"])
            .arg(&wrong_key_path)
            .args(["2048"])
            .status()
            .unwrap()
            .success()
    );

    let signer_cert_pem = std::fs::read(&signer_cert_path).unwrap();
    let wrong_key_pem = std::fs::read(&wrong_key_path).unwrap();

    let err = CmsSigner::new(&signer_cert_pem, &wrong_key_pem)
        .err()
        .expect("should fail when RSA private key doesn't match certificate");
    assert!(
        err.to_string().contains("does not match"),
        "error should indicate key mismatch, got: {}",
        err
    );
}

#[test]
fn test_ed25519_key_mismatch() {
    let temp_dir = tempfile::tempdir().expect("failed to create temp dir");
    let dir = temp_dir.path();

    let ee_ext_path = dir.join("ee.ext");
    std::fs::write(
        &ee_ext_path,
        "basicConstraints=critical,CA:FALSE\nkeyUsage=digitalSignature\n",
    )
    .expect("failed to write EE extensions");

    // Generate a root CA.
    let root_key_path = dir.join("root.key");
    let root_cert_path = dir.join("root.crt");
    assert!(
        Command::new("openssl")
            .args(["genpkey", "-algorithm", "ED25519", "-out"])
            .arg(&root_key_path)
            .status()
            .unwrap()
            .success()
    );
    assert!(
        Command::new("openssl")
            .args(["req", "-x509", "-new", "-key"])
            .arg(&root_key_path)
            .args(["-out"])
            .arg(&root_cert_path)
            .args(["-days", "3650", "-subj", "/CN=Test Ed25519 Root CA"])
            .args(["-addext", "basicConstraints=critical,CA:TRUE"])
            .args(["-addext", "keyUsage=keyCertSign,cRLSign"])
            .status()
            .unwrap()
            .success()
    );

    // Generate the signer key and certificate.
    let signer_key_path = dir.join("signer.key");
    let signer_csr_path = dir.join("signer.csr");
    let signer_cert_path = dir.join("signer.crt");
    assert!(
        Command::new("openssl")
            .args(["genpkey", "-algorithm", "ED25519", "-out"])
            .arg(&signer_key_path)
            .status()
            .unwrap()
            .success()
    );
    assert!(
        Command::new("openssl")
            .args(["req", "-new", "-key"])
            .arg(&signer_key_path)
            .args(["-out"])
            .arg(&signer_csr_path)
            .args(["-subj", "/CN=Test Ed25519 Signer"])
            .status()
            .unwrap()
            .success()
    );
    assert!(
        Command::new("openssl")
            .args(["x509", "-req", "-in"])
            .arg(&signer_csr_path)
            .args(["-CA"])
            .arg(&root_cert_path)
            .args(["-CAkey"])
            .arg(&root_key_path)
            .args(["-CAcreateserial", "-out"])
            .arg(&signer_cert_path)
            .args(["-days", "365", "-extfile"])
            .arg(&ee_ext_path)
            .status()
            .unwrap()
            .success()
    );

    // Generate a different Ed25519 key.
    let wrong_key_path = dir.join("wrong.key");
    assert!(
        Command::new("openssl")
            .args(["genpkey", "-algorithm", "ED25519", "-out"])
            .arg(&wrong_key_path)
            .status()
            .unwrap()
            .success()
    );

    let signer_cert_pem = std::fs::read(&signer_cert_path).unwrap();
    let wrong_key_pem = std::fs::read(&wrong_key_path).unwrap();

    let err = CmsSigner::new(&signer_cert_pem, &wrong_key_pem)
        .err()
        .expect("should fail when Ed25519 private key doesn't match certificate");
    assert!(
        err.to_string().contains("does not match"),
        "error should indicate key mismatch, got: {}",
        err
    );
}

#[test]
fn test_ed25519_large_data() {
    let pki = TestPkiEd25519::new();
    let data: Vec<u8> = (0..1024 * 1024).map(|i| (i % 256) as u8).collect();

    let signer =
        CmsSigner::new(&pki.signer_cert_pem, &pki.signer_key_pem).expect("failed to create signer");
    let signature = signer
        .sign(&data)
        .expect("failed to sign large data with Ed25519");

    let verifier = CmsVerifier::new(&pki.root_cert_pem).expect("failed to create verifier");
    let result = verifier
        .verify(&signature)
        .expect("failed to verify large Ed25519 signature");
    assert_eq!(result.content, data);
}
