name: Check and Lint

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check-and-lint:
    name: Check and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
        with:
          install: false
          cache: true
      - name: Install Rust Toolchain
        run: rustup show active-toolchain
      - name: Install Locked Tools
        run: mise install --locked cargo:cargo-deny
      - name: Check
        run: mise run --skip-tools check
